// Note: this fragment shader was generated by ChatGPT

precision mediump float;

varying vec2 v_uv;
uniform sampler2D u_image;
uniform float u_time;

void main() {
  // Normalize UV to [-1, 1]
  vec2 p = v_uv * 2.0 - 1.0;

  float r = length(p);

  // Fisheye strength
  float strength = 2.0; // 0.5 = mild, 1.5 = strong

  // Polar fisheye mapping
  float theta = atan(p.y, p.x);
  float radius = pow(r, strength);

  // Back to Cartesian
  vec2 uv = radius * vec2(cos(theta), sin(theta));

  // Back to [0,1]
  uv = uv * 0.5 + 0.5;

  // Optional subtle breathing animation
  uv += p * sin(u_time * 0.5) * 0.01;

  // Clamp to avoid black edges
  uv = clamp(uv, 0.0, 1.0);

  gl_FragColor = texture2D(u_image, uv);
}
