// Note: this fragment shader was generated by ChatGPT

precision mediump float;

varying vec2 v_uv;
uniform sampler2D u_image;
uniform float u_time;

float rand(vec2 co) {
  return fract(sin(dot(co, vec2(12.9898,78.233))) * 43758.5453);
}

void main() {
  vec2 uv = v_uv;

  float strength = 0.004;

  // horizontal wobble
  uv.x += sin(uv.y * 80.0 + u_time * 10.0) * strength;

  // scanlines
  float scan = sin(uv.y * 800.0) * 0.04;

  // noise
  float noise = rand(uv + u_time) * 0.05;

  vec3 color = texture2D(u_image, uv).rgb;
  color -= scan;
  color += noise;

  gl_FragColor = vec4(color, 1.0);
}
